config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'

  resources :posts do
    resources :comments
  end

  resources :users
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    user = User.find_by_id(session[:user_id])
    post = Post.find_by_id(params[:id])
  end

  def new
    @comment = Comment.new
    @post = Post.find_by_id(params[:id])
  end

  def create
    @user = User.find_by_id(session[:user_id])
    @post = Post.find(params[:post_id])
      @comment = @post.comments.new(comment_params)
      @comment.user_id = @user.id
      @comment.post_id = @post.id
      @comment.save
      redirect_to "/posts/#{@post.id}"
  end

  def edit
    @user = User.find_by_id(session[:user_id])
    @post = Post.find_by_id(params[:id])
    @comment = Comment.find_by_id(params[:id])
  end

  # def show
  #   @comment = Comment.find_by_id(params[:id])
  # end

  def update
    @post = Post.find_by_id(params[:id])
    @comment = Comment.find_by_id(params[:id])
    if @comment.update(comment_params)
      redirect_to "/posts/#{@comment.post_id}"
      flash[:message] = 'Comment Updated'
    else
      flash[:message] = 'Failed To Update Comment'
    end
  end

  def destroy
    @comment = Comment.find_by_id(params[:id])
    @comment.destroy()
    redirect_to '/'
    flash[:message] = "comment Deleted"
  end

  private

    def comment_params
      params.require(:comment).permit(:content, :user_id, :post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user_post = User.find_by_id(session[:user_id])
    @post = Post.new
    @posts = Post.all
  end

  def show
    @post = Post.find_by_id(params[:id])
    @user = User.find_by_id(@post.user_id)
  end

  def new
    @user_post = User.find_by_id(session[:user_id])
    @post = Post.new
  end

  def create
    user = User.find(session[:user_id])
    post = Post.new(posts_params)
    post.user_id = user.id
    if post.save
      redirect_to '/posts'
      flash[:message] = 'Post Created'
    else
      redirect_to '/posts/new'
      flash[:message] = 'Failed To Create Post'
    end
  end

  def edit
    @post = Post.find_by_id(params[:id])
    @comment = Comment.find_by_id(params[:id])
  end

  def update
    @post = Post.find_by_id(params[:id])
    if @post.update(posts_params)
      flash[:message] = 'Post Updated Successfully'
      redirect_to "/posts/#{@post.id}"
    else
      flash[:message] = "Unsuccessful Update"
      render "/posts/#{@post.id}/edit"
    end
  end

  def destroy
    @post = Post.find_by_id(params[:id])
    @post.destroy
    redirect_to '/'
    flash[:message] = 'Post Deleted'
  end

  private

    def posts_params
      params.require(:post).permit(:title, :content, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
		@user = User.find_by_username(params[:username])

		if @user && @user.authenticate(params[:password])
			session[:user_id] = @user.id
			flash[:message] = "Login successful"
			redirect_to "/users/#{@user.id}"
		else
			flash[:message] = "Login failed"
			redirect_to "/login"
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:message] = "Logout successful"
		redirect_to '/'
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find_by_id(params[:id])
    @posts = @user.posts
  end

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      redirect_to '/users'
      flash[:message] = 'Account Successfully Created'
    else
      flash[:message] = 'Try Again'
      render '/users/new'
    end
  end

  def edit
    @user = User.find_by_id(session[:user_id])
  end

  def update
    @user = User.find_by_id(session[:user_id])
    if @user.update(user_params)
      redirect_to '/users/show'
      flash[:message] = "Account Information Updated"
    else
      flash[:message] = "Failed To Update Account"
      redirect_to "/users/#{session[:user_id]}/edit"
    end
  end

  def destroy
    @user = User.find_by_id(session[:user_id])
    @user.destroy()
    session[:user_id] = nil
    flash[:message] = 'Account Deleted'
    redirect_to '/'
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.html.erb
<div class="container">
  <%= form_for @comment, url: {action: 'update'} do |f| %>

    <div>
      <%= f.text_area :content %>
    </div>

    <%= f.submit %>
  <% end %>

  <%= link_to 'Delete Comment', post_comment_path, method: :delete %>
</div>

app/views/comments/new.html.erb
<div class="container">
  <%form_for [@post, @post.comments.build] do |f| %>
    <div>
      <%= f.text_area :content %>
    </div>
    <%= f.submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewBlog</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <label for="menuBtn" class="menuLabel">Menu</label>
      <input type="checkbox" id="menuBtn" role="button">
      <div class="navbar">
        <nav>
          <ul class="navLeft">
            <!-- <li id="closeMenu"><a href="#">Close Menu</a></li> -->
            <li><a href="/">Home</a></li>
            <li><a href="/users">List of Users</a></li>
            <% if session[:user_id] == nil %>
            <li><a href="/users/new">Sign Up</a></li>
            <li><a href="/login">Login</a></li>
            <% end %>
            <% if session[:user_id] %>
            <li><a href="/posts/new">Create a Post</a></li>
            <li><a href="/users/<%= session[:user_id] %>">Your  Posts</a></li>
          </ul>
          <ul class="navRight">
            <li><a href="/users/<%= session[:user_id] %>/edit">Settings</a></li>
            <li><%= link_to "Log Out", logout_path, method: :get %></li>
            <% end %>
          </ul>
        </nav>
      </div>
      <%# flash[:message] if flash[:message] %>
      <% flash.each do |key, value| %>
        <div class="alert-<%= key %>"><%= value %></div>
      <% end %>
      <div class="content">
        <%= yield %>
      </div>
    </div>
    <footer class="mainFoot">
      Blogger &#169; 2018
    </footer>
    <!-- <script>
      // const mq = window.matchMedia( "(min-width: 510px)" );
      // var close = document.getElementById('closeMenu');
      var nav = document.getElementsByClassName('navbar')[0];
      var content = document.getElementsByClassName('content')[0];
      if (nav.style.display = 'none') {
        menuBtn.addEventListener('click', function() {
          nav.style.display = 'block';
          // menuBtn.style.display = 'none';
          content.style.paddingTop = '0';
          close.style.display = 'block';
        });
      } else {
        nav.addEventListener('click', function() {
          nav.style.display = 'none';
          menuBtn.style.display = 'block';
          content.style.paddingTop = '4em';
        });
      }
    </script> -->
  </body>
</html>

app/views/posts/edit.html.erb
<div class="container">
  <h2>Edit Post</h2>

  <%= form_for @post do |f| %>

    <div><%= f.text_field :title %></div>
    <div><%= f.text_area :content %></div>
    <div><%= f.submit %></div>

  <% end %>
</div>

app/views/posts/index.html.erb
<div class="container">
  <h2>Recent Posts</h2>

  <% @posts.each do |t| %>

    <div>
      <a href="/posts/<%= t.id %>"><%= t.title %></a>
    </div>

  <% end %>
</div>

app/views/posts/new.html.erb
<div class="container">
  <h1>Create A Post</h1>
  <%= form_for @post do |f| %>
    <%= f.text_field :title, placeholder: 'title', required: true %><br>
    <%= f.text_area :content, placeholder: 'content'%><br>
    <%= f.submit value: 'Submit'%>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="container">
  <h1><% @post.title %></h1>

  <div> <%= @post.content %></div>

  <div>Created By: <%= @user.username %></div>

  <% if session[:user_id] == @post.user_id %>

    <%= link_to 'Edit', edit_post_path, method: :get %>
    <%= link_to "Delete", post_path, method: :delete %>

  <% end %>

  <% @post.comments.each do |t| %>

    <div>
      <% user = User.find_by_id(t.user_id) %>
      <%= user.username %> said: <%= t.content %>
  
      <% if session[:user_id] == t.user_id %>
        <a href="/posts/<%= @post.id %>/comments/<%= t.id %>/edit">Edit</a>
      <% end %>
    </div>
  <% end %>

  <% if session[:user_id] %>
    <%= form_with(model: [@post, @post.comments.build]) do |f| %>
    <div>
      <%= f.text_area :content %>
    </div>
    <%= f.submit 'Comment'%>
    <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <h1>Edit Account</h1>

  <%= form_for @user do |t| %>
    <div><%= t.text_field :username, placeholder: 'New Username' %></div>
    <div><%= t.text_field :password, placeholder: 'New Password' %></div>
    <%= t.submit %>
  <% end %>
  <input id="deleteBtn" type="button" value="Delete Account">
  <div id="deleteConfirm" style='display: none'>
    <%= link_to "Confirm Delete Account", user_path, method: :delete %>
  </div>
</div>

<script type="text/javascript">
  var deleteBtn = document.getElementById('deleteBtn');
  var deleteConfirm = document.getElementById('deleteConfirm')
  deleteBtn.addEventListener('click', function () {
  deleteConfirm.style.display = 'block';
  });
</script>

app/views/users/index.html.erb
<div class="container">
  <h1>List of all Users</h1>

    <% @users.each do |u| %>
      <div>
        <a href="/users/<%= u.id %>"><%= u.username %></a>
      </div>
    <% end %>
</div>

app/views/users/new.html.erb
<div class="container">
  <h1>Sign Up</h1>

  <%= form_for @user do |f| %>
    <div><%= f.text_field :username, placeholder: 'Username' %></div>
    <div><%= f.password_field :password, placeholder: 'Password' %></div>
    <%= f.submit %>

  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <h1><%= @user.username %>'s posts</h1>

  <% @posts.each do |t| %>

    <div>
      <a href="/posts/<%= t.id %>"><%= t.title %></a>
    </div>

  <% end %>
</div>